version: '3'

services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    tty: true
  app:
    build:
      context: ./Go
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  proxy:
    build: ./nginx
    ports:
      - 8082:80
    depends_on:
      - app
